name: sars_spike_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pandas=2.2.2
  - biopython=1.85
  - xlsxwriter=3.2.5
  - openpyxl=3.1.2
  - cutadapt=4.8
  - minimap2=2.28
  - samtools=1.21
  - vsearch=2.28.1
  - mmseqs2=15.6f452
  - mafft=7.526
